name: MessageAppMVVM
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++20
      IPHONEOS_DEPLOYMENT_TARGET: '16.2'
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++20
      IPHONEOS_DEPLOYMENT_TARGET: '16.2'
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    exactVersion: 10.6.0
targets:
  MessageAppMVVM:
    platform: iOS
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"MessageAppMVVM/Preview Content"'
          DEVELOPMENT_TEAM: SA7CURWJV7
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.hide0101.message.app.mvvm.dev.MessageAppMVVM
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
        Release:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"MessageAppMVVM/Preview Content"'
          DEVELOPMENT_TEAM: SA7CURWJV7
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.hide0101.message.app.mvvm.dev.MessageAppMVVM
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
    sources:
    - name: MessageAppMVVM
      path: MessageAppMVVM
    type: application
    prebuildScripts:
      - path: ./Scripts/swiftgen.sh
        name: Generate Resources With Swiftgen
  MessageAppMVVMTests:
    dependencies:
    - target: MessageAppMVVM
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: SA7CURWJV7
          GENERATE_INFOPLIST_FILE: 'YES'
          IPHONEOS_DEPLOYMENT_TARGET: '16.2'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.hide0101.message.app.mvvm.dev.MessageAppMVVMTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/MessageAppMVVM.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MessageAppMVVM
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: SA7CURWJV7
          GENERATE_INFOPLIST_FILE: 'YES'
          IPHONEOS_DEPLOYMENT_TARGET: '16.2'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.hide0101.message.app.mvvm.dev.MessageAppMVVMTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/MessageAppMVVM.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MessageAppMVVM
    sources:
    - name: MessageAppMVVMTests
      path: MessageAppMVVMTests
    type: bundle.unit-test
  MessageAppMVVMUITests:
    dependencies:
    - target: MessageAppMVVM
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: SA7CURWJV7
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.hide0101.message.app.mvvm.dev.MessageAppMVVMUITests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_TARGET_NAME: MessageAppMVVM
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: SA7CURWJV7
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.hide0101.message.app.mvvm.dev.MessageAppMVVMUITests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_TARGET_NAME: MessageAppMVVM
    sources:
    - name: MessageAppMVVMUITests
      path: MessageAppMVVMUITests
    type: bundle.ui-testing
